name: Github Pages
on:
  push:
    branches:
      - main
jobs:
  build-gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: npm i
      - name: build
        run: npm run build
      - name: push artifacts
        run: npm run deploy